"use client";

import Link from "next/link";
import { Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { Card, CardHeader } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { EvidenceReportPreview } from "@/components/EvidenceReportPreview";
import { ReportsBuilder } from "@/components/ReportsBuilder";
import { COMPLIANCE_REPORTS } from "@/lib/mock-data";
import { useBundle, useSupplierBundles } from "@/lib/case-store";
import { formatDate } from "@/lib/utils";
import { FileText } from "lucide-react";

export default function ReportsPage() {
  return (
    <Suspense fallback={<ReportsSkeleton />}>
      <ReportsInner />
    </Suspense>
  );
}

function ReportsInner() {
  const searchParams = useSearchParams();
  const bundles = useSupplierBundles();

  const queryId = searchParams.get("supplier") ?? undefined;
  const selectedId = queryId ?? COMPLIANCE_REPORTS[0]?.supplierId ?? bundles[0]?.supplier.id;
  const selectedBundle = useBundle(selectedId ?? "");

  return (
    <div className="space-y-6">
      <div>
        <p className="text-[11px] font-medium uppercase tracking-wider text-canopy-700">Reports</p>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight text-ink-900">
          Compliance evidence reports
        </h1>
        <p className="mt-1 text-sm text-ink-500">
          Generate satellite-backed due diligence reports per supplier. Reports include the 2020 baseline composite,
          current composite, NDVI &amp; SAR trend charts, alert history, and a risk score explanation.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-[320px_1fr]">
        <div className="space-y-4">
          <Card>
            <CardHeader title="Recent reports" subtitle="Generated by the compliance team" />
            <ul className="space-y-2">
              {COMPLIANCE_REPORTS.map((r) => {
                const b = bundles.find((x) => x.supplier.id === r.supplierId);
                if (!b) return null;
                const active = r.supplierId === selectedId;
                return (
                  <li key={r.id}>
                    <Link
                      href={`/reports?supplier=${r.supplierId}`}
                      className={`flex items-start gap-3 rounded-lg border p-3 transition ${
                        active ? "border-canopy-300 bg-canopy-50" : "border-ink-200/70 bg-white hover:bg-ink-50/60"
                      }`}
                    >
                      <div className="mt-0.5 flex h-8 w-8 items-center justify-center rounded-md bg-canopy-100 text-canopy-700">
                        <FileText className="h-4 w-4" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-sm font-medium text-ink-900">{b.supplier.name}</p>
                        <p className="text-[11px] text-ink-500">
                          <span className="font-mono">{r.id}</span> · {formatDate(r.generatedAt)}
                        </p>
                        <div className="mt-1.5 flex items-center gap-1.5">
                          <Badge tone={r.classification}>{r.classification}</Badge>
                          <span className="font-mono text-[10px] text-ink-500">score {r.riskScore}</span>
                        </div>
                      </div>
                    </Link>
                  </li>
                );
              })}
            </ul>
          </Card>

          <ReportsBuilder selectedId={selectedId} />
        </div>

        <div>
          {selectedBundle ? (
            <EvidenceReportPreview bundle={selectedBundle} />
          ) : (
            <Card className="flex h-80 items-center justify-center">
              <p className="text-sm text-ink-500">Select a supplier to preview a report.</p>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

function ReportsSkeleton() {
  return (
    <div className="flex h-96 items-center justify-center text-sm text-ink-500">Loading reports…</div>
  );
}
