// Alert engine: turns raw satellite signals into structured Alert objects
// that move through the supplier review workflow.

import type {
  Alert,
  AlertSeverity,
  AlertType,
  NDVIObservation,
  SARObservation,
  SatelliteMetric,
  SupplierBoundary,
} from "@/lib/types";
import { calculateNDVIAnomaly, detectPersistentBareSoil, detectSARCanopyDisturbance } from "@/lib/satellite";

let alertSeq = 1000;
function nextAlertId(supplierId: string): string {
  alertSeq += 1;
  return `ALT-${supplierId.slice(-4).toUpperCase()}-${alertSeq}`;
}

function severityFromConfidence(conf: number): AlertSeverity {
  if (conf >= 0.85) return "critical";
  if (conf >= 0.65) return "high";
  if (conf >= 0.4) return "medium";
  return "low";
}

function persistenceLabel(months: number): Alert["persistence_status"] {
  if (months >= 6) return "permanent_likely";
  if (months >= 3) return "persistent";
  if (months >= 1) return "monitoring";
  return "transient";
}

export interface BuildAlertsInput {
  supplierId: string;
  satellite: SatelliteMetric;
  boundary: SupplierBoundary;
  ndvi: NDVIObservation[];
  sar: SARObservation[];
}

export function buildAlertsForSupplier(input: BuildAlertsInput): Alert[] {
  const out: Alert[] = [];
  const { supplierId, satellite, boundary, ndvi, sar } = input;

  // 1. NDVI anomaly on most recent observation.
  if (ndvi.length > 0) {
    const last = ndvi[ndvi.length - 1];
    const anomaly = calculateNDVIAnomaly(last.ndvi, last.seasonalBaselineNdvi);
    if (anomaly.isSignificant) {
      const affectedPct = Math.min(100, Math.abs(anomaly.anomalyPct) * 1.4);
      const conf = Math.min(0.9, 0.45 + Math.abs(anomaly.anomalyPct) / 100);
      out.push({
        alert_id: nextAlertId(supplierId),
        supplier_id: supplierId,
        alert_type: "vegetation_anomaly",
        severity: severityFromConfidence(conf),
        confidence: round(conf, 2),
        first_detected_date: last.date,
        affected_area_hectares: round((affectedPct / 100) * boundary.areaHectares, 1),
        affected_area_percentage: round(affectedPct, 1),
        ndvi_change_percentage: anomaly.anomalyPct,
        sar_confirmation_level: "none",
        persistence_status: "monitoring",
        external_alert_match: satellite.externalAlertMatchCount > 0,
        recommended_action:
          "Possible forest disturbance detected — request supplier explanation and monitor next two satellite passes.",
        evidence_summary: `NDVI dropped ${Math.abs(anomaly.anomalyPct).toFixed(1)}% below same-season baseline on ${last.date}.`,
        status: "new",
        decisionLog: [seedDecision("System", "Alert generated by NDVI anomaly detector.")],
      });
    }
  }

  // 2. SAR canopy disturbance — confirms an NDVI signal when present.
  if (sar.length > 2) {
    const last = sar[sar.length - 1];
    const baseline = sar[Math.max(0, sar.length - 6)];
    const sarResult = detectSARCanopyDisturbance(last, baseline);
    if (sarResult.level !== "none") {
      const conf = sarResult.level === "strong" ? 0.88 : sarResult.level === "moderate" ? 0.7 : 0.5;
      out.push({
        alert_id: nextAlertId(supplierId),
        supplier_id: supplierId,
        alert_type: "sar_canopy_disturbance",
        severity: severityFromConfidence(conf),
        confidence: conf,
        first_detected_date: last.date,
        affected_area_hectares: round(boundary.areaHectares * 0.18, 1),
        affected_area_percentage: 18,
        ndvi_change_percentage: 0,
        sar_confirmation_level: sarResult.level,
        persistence_status: "monitoring",
        external_alert_match: satellite.externalAlertMatchCount > 0,
        recommended_action:
          "SAR-confirmed canopy structure change. Escalate to supplier engagement and queue audit if not explained within 14 days.",
        evidence_summary: `Sentinel-1 VV backscatter increased by ${sarResult.delta.toFixed(2)} dB vs rolling baseline.`,
        status: "new",
        decisionLog: [seedDecision("System", "Alert generated by SAR disturbance detector.")],
      });
    }
  }

  // 3. Persistent bare soil.
  const persistence = detectPersistentBareSoil(ndvi);
  if (persistence.isPersistent) {
    const conf = Math.min(0.95, 0.55 + persistence.months * 0.05);
    out.push({
      alert_id: nextAlertId(supplierId),
      supplier_id: supplierId,
      alert_type: "persistent_bare_soil",
      severity: severityFromConfidence(conf),
      confidence: conf,
      first_detected_date: persistence.lastBareDate ?? satellite.lastObservationDate,
      affected_area_hectares: round(boundary.areaHectares * 0.45, 1),
      affected_area_percentage: 45,
      ndvi_change_percentage: -45,
      sar_confirmation_level: "moderate",
      persistence_status: persistenceLabel(persistence.months),
      external_alert_match: satellite.externalAlertMatchCount > 0,
      recommended_action:
        "Bare-soil condition has persisted beyond a typical harvest/replanting cycle. Likely land conversion — schedule audit.",
      evidence_summary: `Bare soil observed in ${persistence.months} consecutive months without a recovery/replanting NDVI signature.`,
      status: "new",
      decisionLog: [seedDecision("System", "Alert generated by persistence detector.")],
    });
  }

  // 4. Post-2020 forest loss.
  const lossPct = Math.max(
    0,
    satellite.baselineForestCoverPct - satellite.currentForestCoverPct,
  );
  if (lossPct >= 2) {
    const conf = Math.min(0.92, 0.5 + lossPct / 50 + satellite.externalAlertMatchCount * 0.05);
    out.push({
      alert_id: nextAlertId(supplierId),
      supplier_id: supplierId,
      alert_type: "post_2020_forest_loss",
      severity: severityFromConfidence(conf),
      confidence: round(conf, 2),
      first_detected_date: satellite.lastObservationDate,
      affected_area_hectares: round(boundary.areaHectares * (lossPct / 100), 1),
      affected_area_percentage: round(lossPct, 1),
      ndvi_change_percentage: -Math.round(lossPct * 1.2),
      sar_confirmation_level:
        satellite.externalAlertMatchCount > 3 ? "strong" : satellite.externalAlertMatchCount > 0 ? "moderate" : "weak",
      persistence_status: "persistent",
      external_alert_match: satellite.externalAlertMatchCount > 0,
      recommended_action:
        "Likely vegetation loss signal vs 2020 baseline. Request supplier evidence (replanting plan, change-of-use documentation).",
      evidence_summary: `Forest cover ${satellite.baselineForestCoverPct.toFixed(1)}% → ${satellite.currentForestCoverPct.toFixed(1)}% since 2020 baseline. Requires human review.`,
      status: "new",
      decisionLog: [seedDecision("System", "Alert generated by 2020 baseline comparator.")],
    });
  }

  // 5. Protected area overlap.
  if (boundary.protectedAreaOverlapHectares > 0) {
    out.push({
      alert_id: nextAlertId(supplierId),
      supplier_id: supplierId,
      alert_type: "protected_area_overlap",
      severity: "high",
      confidence: 0.95,
      first_detected_date: boundary.uploadedAt,
      affected_area_hectares: boundary.protectedAreaOverlapHectares,
      affected_area_percentage: round(
        (boundary.protectedAreaOverlapHectares / boundary.areaHectares) * 100,
        1,
      ),
      ndvi_change_percentage: 0,
      sar_confirmation_level: "none",
      persistence_status: "persistent",
      external_alert_match: false,
      recommended_action:
        "Supplier boundary intersects a protected / HCV area. Suspend procurement pending investigation.",
      evidence_summary: `${boundary.protectedAreaOverlapHectares.toFixed(0)} ha of the supplier boundary overlaps a WDPA polygon.`,
      status: "new",
      decisionLog: [seedDecision("System", "Alert generated by protected area cross-check.")],
    });
  }

  // 6. Boundary quality issue.
  if (boundary.quality === "low" || boundary.quality === "needs_review") {
    out.push({
      alert_id: nextAlertId(supplierId),
      supplier_id: supplierId,
      alert_type: "boundary_quality_issue",
      severity: "medium",
      confidence: 1,
      first_detected_date: boundary.uploadedAt,
      affected_area_hectares: boundary.areaHectares,
      affected_area_percentage: 100,
      ndvi_change_percentage: 0,
      sar_confirmation_level: "none",
      persistence_status: "transient",
      external_alert_match: false,
      recommended_action:
        "Request a higher-fidelity GeoJSON or KML boundary from the supplier to reduce monitoring uncertainty.",
      evidence_summary: `Boundary quality scored ${boundary.qualityScore}/100 with ${boundary.validationIssues.length} validation issue(s).`,
      status: "under_review",
      decisionLog: [seedDecision("System", "Boundary validation surfaced data-quality concerns.")],
    });
  }

  // 7. External forest alert match (only emit if not already represented).
  if (satellite.externalAlertMatchCount >= 3) {
    out.push({
      alert_id: nextAlertId(supplierId),
      supplier_id: supplierId,
      alert_type: "external_forest_alert_match",
      severity: "high",
      confidence: 0.85,
      first_detected_date: satellite.lastObservationDate,
      affected_area_hectares: round(boundary.areaHectares * 0.12, 1),
      affected_area_percentage: 12,
      ndvi_change_percentage: -15,
      sar_confirmation_level: "moderate",
      persistence_status: "monitoring",
      external_alert_match: true,
      recommended_action:
        "Multiple external forest alert systems flagged this polygon. Combine with internal evidence and escalate.",
      evidence_summary: `${satellite.externalAlertMatchCount} matching alerts across RADD / GLAD-S2 / GFW Integrated in the monitoring window.`,
      status: "new",
      decisionLog: [seedDecision("System", "External alert cross-check produced concurrent signals.")],
    });
  }

  return out;
}

function seedDecision(actor: string, action: string) {
  return {
    date: new Date().toISOString(),
    actor,
    action,
  };
}

function round(n: number, decimals: number): number {
  const f = 10 ** decimals;
  return Math.round(n * f) / f;
}
